data:
  name: 'test-deepsea-logistic'
  path: '/scratch/midway2/xinhe/repo/deep_variant/peak2binary/output/test/merged.hdf5'
feature:
  name: 'deepsea'
  path: '/project2/xinhe/yanyul/deep_variant/yanyu/DeepSEA/debug/keras_deepsea_feature_12.hdf5'
classifier:
  type: 'logistic'  ## svm
  param: '0_0'  ## logistic: l1_l2; svm: 0_l2 since l1 won't be used anyway  
fold: 5
