call_varscan: 'java -jar /project2/xinhe/yanyul/softwares/varscan/VarScan.v2.4.3.jar'
fastq:
  E081:
    1: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203400.fastq.gz'
    2: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203401.fastq.gz'
    3: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203402.fastq.gz'
    4: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203403.fastq.gz'
    5: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203404.fastq.gz'
    6: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203405.fastq.gz'
    7: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203406.fastq.gz'
    8: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203407.fastq.gz'
    9: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203408.fastq.gz'
    10: '../../../deep_variant/yanyu/deep_brain/evaluate_by_DGF/SRX062364/SRR203409.fastq.gz'
genome_assembly:
  fasta: '/project2/xinhe/yanyul/databases/hg19/hg19.fa'
  size: '/project2/xinhe/yanyul/database/hg19/hg19.chrom.sizes'
ncpus: 20
model:
  name: 'keras_deepsea_copy'
  snakemake: 'modules/submodules/input2score/_train_model_do_nothing.snakemake'
  workdir: '../../yanyu/DeepSEA/debug'
  label_idx: 920 # 1-based
