---
title: "Task"
author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# Data preparation

We need to incorporate new data (fetal brain related) to the model. It contains two sub tasks:

1. Annotate DeepSEA sequence with new labels.
    - See pipeline memo [here](memo_preprocessing.html) for E081, E082, Noonan, E129 (DeepSEA label)
    - See pipeline memo [here](memo_preprocessing_ATACseq.html) for ATAC-seq data from Noonan's lab
    - See pipeline memo [here](memo_preprocessing_GSE70823.html) for d27-NSC, d41-neuron data from GSE70823
    - See pipeline memo [here](memo_preprocessing_atac_seq_053018.html) for ATAC-seq data obtained from Yifan 5/30/18
2. Extract new sequences of interest based on new data set.
    - See pipeline memo [here](memo_extract.html) for E081, E082, Noonan, E129 (DeepSEA label)
    - See pipeline memo [here](memo_extract_ATACseq.html) for ATAC-seq data from Noonan's lab
    - See pipeline memo [here](memo_extract_GSE70823.html) for d27-NSC, d41-neuron data from GSE70823
    - See pipeline memo [here](memo_extract_ATACseq053018.html) for ATAC-seq data obtained from Yifan 5/30/18
3. Define positive and negative sequences
    - See memo [here](memo_posneg_fantom.html) for fantom fetal brain cage peak from Zhongshan (06/02/18)

# Genomic Data

1. Stage1
    - Fetal brain DNase-seq from Roadmap (E081, E082)
    - H3K27ac mark from Noonan's lab (Noonan)
    - One label from Deepsea model (E129)
2. Stage2
    - ATAC-seq data from Noonan's lab (hNSC-50, hNSC-P15-1, hNSC-P5-1, hNSC-P5-2)
3. paperNSC
    - NSC data from this [paper](https://www.ncbi.nlm.nih.gov/pubmed/28803920) and the data is obtained from this [link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE70823)
    - d27, d41-1, d41-2 data are used
    - Is referred as `paperNSC`
4. ATAC053018
    - Obtained from Yifan on 5/30/18
    - Contains cell types labelled as `CN`, `DN`, `GA`, `ips`, `NSC`

# Train new models

There are three strategies:

0. Baseline classifier. [here](baseline.html)
    - Train an SVM or logistic classifier using JASPAR as annotation
    - Gkm-SVM classifier is trained on 5000 positive and 5000 negative sequences one annotation at a time.

1. Use DeepSEA sequences and DeepSEA feature representation.
    - See training result [Stage1 here](type1.html).
    - See performance on new sequences [Stage1 here](type1_newseq.html)
    - Evalution using allelic imbalance site [Stage1 here](type1_allelic_imbalance.html)
2. Use DeepSEA sequences but train a new model using the same architecture as DeepSEA.
    - See results and analysis [Stage1 here](type2.html). **Leave for future**
3. Include new sequences and train a new model using the same architecture. **Leave for future**

# Results

1. ROC/PR curve
    - [Stage1, JASPAR logistic, deepsea+extracted, no reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/JASPAR_plot.html)
    - [Stage1 JASPAR logistic, deepsea+extracted, reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/JASPAR.reweight_plot.html)
    - [Stage1 gkmsvm, deepsea, no reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/type1.gkm_deepsea_plot.html)
    - [Stage1 gkmsvm, deepsea, reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/type1.gkm_deepsea.reweight_plot.html)
    - [Stage1, train_deepsea, deepsea+extracted, no reweight](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/pr_roc_curve/report/deepsea_vs_newseq_plot.html)
    - [Stage1, train_deepsea, deepsea+extracted, reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/type1.reweight_plot.html)
    - [Stage1 Stage2, all methods, deepsea sequence, reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/deepsea-stage1stage2.reweight_plot.html)
    - [Stage1 Stage2, all methods, extracted sequence, reweight](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/extracted-stage1stage2.reweight_plot.html)
    - [Stage1 Stage2, all methods, extracted sequence, reweight, 080917 For Xin](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/template/plot_roc_e081e082.html),
    - [paperNSC, all methods, deepsea sequences, reweighted GC](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/deepsea-paperNSC.reweight_plot.html),
    - [paperNSC, all methods, extracted sequences, reweighted GC](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/extracted-paperNSC.reweight_plot.html)
    - [ATACseq 05/30/18 from Yifan, DeepSEA sequences](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/deepsea-ATAC053018.reweight_plot.html)
    - [ATACseq 05/30/18 from Yifan, extracted sequences](https://rawgit.com/liangyy/deep_variant/code/pr_roc_curve/report/extracted-ATAC053018.reweight_plot.html)
2. AUC scores
    - [Stage1, train_deepsea vs. JASPAR, no reweight](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/report/deep_brain.auc_comparison.html)
    - [Stage1, train_deepsea vs. JASPAR, reweight](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/report/deep_brain_reweight.auc_comparison.html)
    - [Stage1, train_deepsea vs. gkmsvm, reweight](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/report/gkm_vs_type1_on_deepsea_test.auc_comparison.html)
    - [Stage1 Stage2, compare all methods, reweight](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/report/deep_brain-stage1stage2.auc_comparison.html)
    - [Stage1 Stage2, compare all methods, reweight, by group](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/template/auc_summary_bygroup.html),
    - [paperNSC, all methods, reweighted GC](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/report/deep_brain-paperNSC.auc_comparison.html)

# Other analysis

There are some other directions and issues we need to explore and tackle. The analysis of them are listed here.

1. **Motif Analysis**:
    - Examine which filter or a set of filters that contribute most to a particular prediction task. See details
      [Stage1 here](motif_analysis.html). **ONGOING**

2. **Training Strategy**
    - How to boost the model to specialize on a particular prediction task, say on certain tissue type? (change architecture? how to deal with overfitting?) **TODO**

3. **Performance Evaluation**
    - How to measure the performance on imbalanced data. For instance, how to interpret ROC AUC and PR AUC? See related discussion
      [here](auc.html)
    - Redo DeepSEA evaluation on DNase footprint data (See Allelic Imbalance Analysis below)

4. **Application**
    - IBD GWAS SNPs. See [here](SNP_enrichment.html) Rmarkdown script is at [here](https://uchicago.box.com/s/zdntptc8udymivtyoapxpu365rpo3b18)

5. **Data Quality**:
    - GC content.
        * [Stage1 DeepSEA test set](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/deepsea.gc_content.html),
        * [Stage1 Sequences extracted from BED file](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/extracted.gc_content.html)
        * [Stage2 Deepsea sequence set](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/deepsea-ATACseq.gc_content.html)
        * [Stage2 Extracted sequence set](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/extracted-ATACseq.gc_content.html)
        * [paperNSC DeepSEA sequences](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/deepsea-paperNSC.gc_content.html)
        * [paperNSC Extracted sequences](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/extracted-paperNSC.gc_content.html)
        * [ATACseq 05/30/18 from Yifan, DeepSEA sequence set](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/deepsea-ATAC053018.gc_content.html)
        * [ATACseq 05/30/18 from Yifan, extracted sequence set](https://rawgit.com/liangyy/deep_variant/code/gc_content/report/extracted-ATAC053018.gc_content.html)
    - Similarity between data sets
      [Stage1 Stage2 with Normal Brain data from DeepSEA](https://rawgit.com/liangyy/deep_variant/code/annotation_overlap/report/distance.stage1stage2.html)

6. **Allelic Imbalance Analysis**:
    - DeepSEA results (Table S3). Presented by data set at [here](allelic_imbalance_deepsea.html)
    - Rerun analysis considering both imbalanced variants and balanced variants
      [here](allelic_imbalance_rerun.html)

7. **Detecting Regulartory Grammar**:
    - Critical windows are used to detect important "word" in the sequence and potentially the combination of "word" ("phrase") in the sequence. Here, we first explore the distribution of critical window along the sequence.  [E081](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/Type1/newseq.matchgc.E081_sliding_window.signal_block.MaskSize_10.html),
[Noonan](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/Type1/newseq.matchgc.Noonan_sliding_window.signal_block.MaskSize_10.html)

# TODO list

* 4/9/17:
    1. ~~ROC/PR AUC interpretation~~ [link](auc.html)
    2. ~~Extract sequences from new data sets~~ [link](memo_extract.html)
* 4/10/17:
    3. New loss function? Weighted hinge loss? [link](loss_function.html) **TODO**
    4. Motif analysis of current model [link](motif_analysis.html) **ONGOING**
* 4/14/17:
    5. ~~Build up pipeline using snakemake.~~ See issue1 at [link](https://github.com/CreRecombinase/DeepVariantPrediction)
* 4/26/17:
    6. ~~Build baseline classifier~~ [link](baseline.html)
* 5/29/17:
    7. GC content bias in training and testing data
        - To overcome this, we can either use unbiased sequence set or reweight the performance evaluation function based on the GC content.
        - At first, do reweighting (~~testing~~ - training - ~~motif analysis~~) **ONGOING** see [testing with reweight](https://rawgit.com/liangyy/deep_variant/code/performance_comparison/report/deep_brain_reweight.auc_comparison.html) and [motif analysis with gc matched sequences](motif_analysis.html)
        - Construct a sequence set with matched GC content in positive and negative instances (use Homer?) **TODO**
* 5/31/17:
    8. Search for motif hits using top 20 motifs in motif activation analysis by GC matched sequences **TODO**
