---
title: "Deep brain - Motif analysis"
author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
    
<style>
pre code, pre, code {
    white-space: pre !important;
    overflow-x: scroll !important;
    word-break: keep-all !important;
    word-wrap: initial !important;
}
</style>
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=2000)
```

# Motivation

To investigate whether DeepSEA captures features related to known TFs in fetal brain. Here we focus on the first convolutional layer because it can be interpreted as motif detection layer.

# Strategies
Our goal can be formalized as: for a set of input sequences which k-mer pattern contirbute most to a particular prediction task. The followings list three strategies to implement it:

1. For each sequence, do in silico mutation for each site and extract k-mer (may use something looser, like (k+m)-mer) surrounding the peak. Aggregate all k-mers collected and extract the common pattern from them.
2. For each sequence, calculate the derivative of output w.r.t. motif neuron, where the spatial information should be collapsed properly. Aggregate all motif neuron contribution patterns to find the neuron or combination of neurons that contribute most.
3. For each sequence, calculate the activation of motif neuron (still we need to collapse spatial information properly). Aggregate all motif activation patterns to find the neuron or combination of neurons that are activated most.

# Analysis

0.1. Sequences selection:
    - We would like to focus on sequences that are correctly predicted by our model, namely low-score negative instances and high-score positive instances.
    - GC content and score distribution [matched_gc](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/select_sequence/newseq.matchgc.gc.html)
0.2. Motif visualization: see [here](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/motif_visualization/draw_list.html), [pwm visualization](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/motif_visualization/pwm.html)
1. Mutagensis **TODO**
2. Sliding window [newseq.E081](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/Type1/newseq.E081_sliding_window.html), [newseq.Noonan](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/Type1/newseq.Noonan_sliding_window.html)
3. Motif gradient [E081](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/E081_motif_gradient.html), [E082](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/E082_motif_gradient.html)
4. Motif activation: see analysis on [E081](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/E081_motif_activation.html), [E082](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/E082_motif_activation.html), [Noonan](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/Noonan_motif_activation.html), [newseq.E081](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/newseq.E081_motif_activation.html), [newseq.Noonan](http://htmlpreview.github.io/?https://github.com/liangyy/deep_variant/blob/code/motif_analysis/report/Type1/newseq.Noonan_motif_activation.html), [matched_gc.E081](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/Type1/newseq.matchgc.E081_motif_activation.html), [matched_gc.Noonan](https://rawgit.com/liangyy/deep_variant/code/motif_analysis/report/Type1/newseq.matchgc.Noonan_motif_activation.html)

# Aligning Extracted Motifs

Database `db/CIS-BP/Homo_sapiens.meme` (see [here](http://cisbp.ccbr.utoronto.ca/)).

1. 5/4/17: top 10 motifs in motif activation of E081, [link](https://liangyy.github.io/deep_variant/TOMTOM_050417.pdf)
2. 5/5/17: Selected motifs by combining motif activation and motif gradient results, [link](https://liangyy.github.io/deep_variant/TOMTOM_050517.pdf)
3. 5/26/17: motifs manually selected from result of motif acitvation pattern in new sequences,
[newseq.E081](https://liangyy.github.io/deep_variant/TOMTOM_newseq.E081.pdf) and 
[newseq.Noonan](https://liangyy.github.io/deep_variant/TOMTOM_newseq.Noonan.pdf)
