---
title: "Deep brain - Type 1 - evaluation on allelic imbalance instances"
# author: Yanyu Liang
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
    
<style>
pre code, pre, code {
        white-space: pre !important;
        overflow-x: scroll !important;
        word-break: keep-all !important;
        word-wrap: initial !important;
    }
</style>
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=2000)
```

```{r}
source('my_r.R')
library(feather)
library(ggplot2)
variant_url <- 'https://github.com/liangyy/deep_variant/blob/code/allelic_imbalance/data/E081.combined.imbalance.gz?raw=true'
variant <- read.table(read_gz_url(variant_url), sep = '\t', header = T)
score_url <- 'https://github.com/CreRecombinase/DeepVariantPrediction/blob/issue1/score/keras_deepsea_with_040417_2_42_head_copy/allelic_imbalance_E081.E081_allelic_imbalance_result.feather?raw=true'
score <- read_feather_url(score_url)
variant$Ref <- NA
variant$Ref[score$Varient.ID] <- score$Allele1
variant$Alt <- NA
variant$Alt[score$Varient.ID] <- score$Allele2
variant$Imbalance <- 'Balanced'
variant$Imbalance[variant$P.Value < 0.01] <- 'Imbalanced'
ggplot(variant) + geom_point(aes(x = Alt, y = Ref, color = log10(Odds.Ratio))) + scale_colour_gradient2() + facet_grid(.~Imbalance) + geom_abline(intercept = 0.07, slope = 1) + geom_abline(intercept = -0.07, slope = 1) + ggtitle('The Predicted Effect of \n Heterozygous sites in DNase-seq of E081')
```