deep_brain:
  deepsea_logistic: '../pr_roc_curve/result/deepsea_vs_newseq_curves.feather'
  jaspar_logistic: '../pr_roc_curve/result/JASPAR_curves.feather'
  jaspar_svm: '../pr_roc_curve/result/JASPAR_svm_curves.feather'
