deep_brain-stage1stage2:
  deepsea: '/project2/xinhe/yanyul/repo/deep_variant/pr_roc_curve/result/deepsea-stage1stage2.reweight_curves.feather'
  extracted: '/project2/xinhe/yanyul/repo/deep_variant/pr_roc_curve/result/extracted-stage1stage2.reweight_curves.feather'
by: 'sequence'
