deep_brain-ATACseq_deepsea_gc:
  deepsea: '/project2/xinhe/yanyul/repo/deep_variant/pr_roc_curve/result/deepsea-ATACseq.reweight_curves.feather'
  deepsea.no-reweight: '/project2/xinhe/yanyul/repo/deep_variant/pr_roc_curve/result/deepsea-ATACseq_curves.feather'
by: 'sequence'
