deep_brain-stage1stage2_deepsea_gc:
  deepsea: '/project2/xinhe/yanyul/repo/deep_variant/pr_roc_curve/result/deepsea-stage1stage2.reweight_curves.feather'
  deepsea.no-reweight: '/project2/xinhe/yanyul/repo/deep_variant/pr_roc_curve/result/deepsea-stage1stage2.no-reweight_curves.feather'
by: 'sequence'
