# This module takes the intermediate output of pr_roc_curve module (the curve feather file) do the bar plot to
# compare the performance of multiple classifiers under multiple data sets

rule calculate_auc:
    input:
        lambda wildcards: config[wildcards.model]
    output:
        'result/auc_{model}.feather'
    shell:
        'python scripts/auc.py --curve {input[0]} --out {output[0]}'
rule summary:
    # input:
    #     [ 'result/auc_{model}.feather'.format(model=model) for model in config ]
    output:
        temp()'report/auc_comparison.Rmd')
    params:
        '--'.join(config)
    run:
        rmd = '''
'''
