wgEncodeUwDgfA549Aln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfA549Aln.bam'
wgEncodeUwDgfAg10803Aln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfAg10803Aln.bam'
wgEncodeUwDgfAoafAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfAoafAln.bam'
wgEncodeUwDgfGm12865Aln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfGm12865Aln.bam'
wgEncodeUwDgfH7esAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfH7esAln.bam'
wgEncodeUwDgfHaeAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHaeAln.bam'
wgEncodeUwDgfHahAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHahAln.bam'
wgEncodeUwDgfHaspAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHaspAln.bam'
wgEncodeUwDgfHcfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHcfAln.bam'
wgEncodeUwDgfHcfaaAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHcfaaAln.bam'
wgEncodeUwDgfHcmAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHcmAln.bam'
wgEncodeUwDgfHcpeAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHcpeAln.bam'
wgEncodeUwDgfHeeAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHeeAln.bam'
wgEncodeUwDgfHffAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHffAln.bam'
wgEncodeUwDgfHgfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHgfAln.bam'
wgEncodeUwDgfHipeAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHipeAln.bam'
wgEncodeUwDgfHmfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHmfAln.bam'
wgEncodeUwDgfHmvecbAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHmvecbAln.bam'
wgEncodeUwDgfHmvecdAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHmvecdAln.bam'
wgEncodeUwDgfHmvecdbladAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHmvecdbladAln.bam'
wgEncodeUwDgfHmvecfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHmvecfAln.bam'
wgEncodeUwDgfHmvechAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHmvechAln.bam'
wgEncodeUwDgfHpafAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHpafAln.bam'
wgEncodeUwDgfHpdlfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHpdlfAln.bam'
wgEncodeUwDgfHpfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHpfAln.bam'
wgEncodeUwDgfHrceAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHrceAln.bam'
wgEncodeUwDgfHsmmAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHsmmAln.bam'
wgEncodeUwDgfHuvecAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHuvecAln.bam'
wgEncodeUwDgfHvmfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfHvmfAln.bam'
wgEncodeUwDgfNb4Aln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfNb4Aln.bam'
wgEncodeUwDgfNhaAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfNhaAln.bam'
wgEncodeUwDgfNhdfadAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfNhdfadAln.bam'
wgEncodeUwDgfNhdfneoAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfNhdfneoAln.bam'
wgEncodeUwDgfNhlfAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfNhlfAln.bam'
wgEncodeUwDgfSaecAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfSaecAln.bam'
wgEncodeUwDgfSkmcAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfSkmcAln.bam'
wgEncodeUwDgfT47dAln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfT47dAln.bam'
wgEncodeUwDgfTh1AlnRep2: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfTh1AlnRep2.bam'
wgEncodeUwDgfTh2Aln: 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwDgf//wgEncodeUwDgfTh2Aln.bam'
