data:
  Chorion-DNase: 3
  NH-A-DNase: 110
  NH-A-CTCF: 161
  NH-A-EZH2: 162
  NH-A-H2AZ: 866
  NH-A-H3K27ac: 867
  NH-A-H3K27me3: 868
  NH-A-H3K36me3: 869
  NH-A-H3K4me1: 870
  NH-A-H3K4me2: 871
  NH-A-H3K4me3: 872
  NH-A-H3K79me2: 873
  NH-A-H3K9ac: 874
  NH-A-H3K9me3: 875
  NH-A-H4K20me1: 876
bed_list: '/project2/xinhe/yanyul/deep_variant/nick/DeepVariantPrediction/metadata/nmeth.3547-S2.csv'
