---
title: "Training - Compare AUCs"
output:
    html_document:
        number_sections: true
        toc: true
        toc_depth: 3
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup}
knitr::opts_knit$set(root.dir = '../')
```

# Distribution of GC content

```{r, echo=FALSE, warning=FALSE}
library(feather)
library(ggplot2)
model_list <- 'deepsea_logistic,jaspar_logistic'
aucs <- c()
for(i in strsplit(model_list, ',')[[1]]){
    temp <- read_feather(paste0('result/auc_', i, '.feather'))
    temp$model <- i
    aucs <- rbind(aucs, temp)
}
aucs$grp <- paste(aucs$model, aucs$info)
temp <- unique(aucs$info)
cols[[temp[1]]] <- 'red'
cols[[temp[2]]] = 'black'
ggplot(aucs) + geom_bar(aes(x = data, y = score, group = grp, color = info, fill = model), stat = 'identity', position = 'dodge') + facet_wrap(~curve) + scale_colour_manual(values = cols) + scale_fill_brewer(palette="OrRd") + labs(color = 'sequence source') + ggtitle('AUCs')
```

```{r}
library(feather)
library(ggplot2)
model_list <- 'deepsea_logistic--jaspar_logistic'
aucs <- c()
for(i in strsplit(model_list, '--')[[1]]){
    temp <- read_feather(paste0('result/auc_', i, '.feather'))
    temp$model <- i
    aucs <- rbind(aucs, temp)
}
aucs$grp <- paste(aucs$model, aucs$info)
temp <- unique(aucs$info)
cols <- c('red', 'black')
names(cols) <- temp
ggplot(aucs) + geom_bar(aes(x = data, y = score, group = grp, color = info, fill = model), stat = 'identity', position = 'dodge') + facet_wrap(~curve) + scale_colour_manual(values = cols) + scale_fill_brewer(palette="OrRd") + labs(color = 'sequence source') + ggtitle('AUCs')
```