reweight: '1'
deepsea-ATAC053018.reweight:
  group1:
    info: 'train_deepsea'
    data:
      CN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/type1-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_CN.gc.feather'
      DN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/type1-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_DN.gc.feather'
      GA:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/type1-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_GA.gc.feather'
      ips:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/type1-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_ips.gc.feather'
      NSC:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/type1-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_NSC.gc.feather'
  group2:
    info: 'JASPAR-logistic'
    data:
      CN:
       y:
         path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
         name: 'traindata'
         label_idx: 1 # 1-based
         double: 'Yes'
         remove: 'None'
       ypred:
         path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-logistic-ATAC053018_deepsea.ypred.hdf5'
         name: 'y_pred'
         label_idx: 1 # 1-based
         double: 'Yes'
         remove: 'None'
       gc: '../gc_content/results/deepsea_CN.gc.feather'
      DN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-logistic-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_DN.gc.feather'
      GA:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-logistic-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_GA.gc.feather'
      ips:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-logistic-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_ips.gc.feather'
      NSC:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-logistic-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_NSC.gc.feather'
  group3:
    info: 'JASPAR-svm'
    data:
      CN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-svm-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_CN.gc.feather'
      DN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-svm-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_DN.gc.feather'
      GA:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-svm-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_GA.gc.feather'
      ips:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-svm-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_ips.gc.feather'
      NSC:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/prediction/result/JASPAR-svm-ATAC053018_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_NSC.gc.feather'
  group4:
    info: 'gkmsvm'
    data:
      CN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/gkm_svm/result/deepsea_train-ATAC053018_CN.3.deepsea_test-ATAC053018.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_CN.gc.feather'
      DN:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/gkm_svm/result/deepsea_train-ATAC053018_DN.2.deepsea_test-ATAC053018.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_DN.gc.feather'
      GA:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/gkm_svm/result/deepsea_train-ATAC053018_GA.3.deepsea_test-ATAC053018.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_GA.gc.feather'
      ips:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/gkm_svm/result/deepsea_train-ATAC053018_ips.1.deepsea_test-ATAC053018.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_ips.gc.feather'
      NSC:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/scratch/midway2/xinhe/repo/deep_variant/gkm_svm/result/deepsea_train-ATAC053018_NSC.2.deepsea_test-ATAC053018.hdf5'
          name: 'y_pred'
          label_idx: 5 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_NSC.gc.feather'

