reweight: '0'
type1.gkm_deepsea:
  group1:
    info: 'deepsea'
    data:
      E081:
        y:
          path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_E081.3.deepsea_test.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_E081_gkm.gc.feather'
      E082:
        y:
          path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_E082.1.deepsea_test.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_E082_gkm.gc.feather'
      E129:
        y:
          path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_E129.3.deepsea_test.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_E129_gkm.gc.feather'
      Noonan:
        y:
          path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_Noonan.2.deepsea_test.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_Noonan_gkm.gc.feather'
