# prefix: 'JASPAR'
reweight: '1'
JASPAR.reweight:
  group1:
    info: 'deepsea'
    data:
      E081:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_E081.gc.feather'
      E082:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_E082.gc.feather'
      E129:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_E129.gc.feather'
      Noonan:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_Noonan.gc.feather'
  group2:
    info: 'new_label'
    data:
      E081:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E081.txt_out/label.hdf5'
          name: 'data/E081-DNase.macs2.narrowPeak.sorted.intersect'
          label_idx: 1 # 1-based
          double: 'No'
          remove: '1073109-1073114'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/E081.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/E081.gc.feather'
      E082:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E082.txt_out/label.hdf5'
          name: 'data/E082-DNase.macs2.narrowPeak.sorted.intersect'
          label_idx: 2 # 1-based
          double: 'No'
          remove: '1238543-1238548'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/E082.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/E082.gc.feather'
      E129:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E129.txt_out/label.hdf5'
          name: 'data/E129-H3K9me3.narrowPeak.sorted.intersect'
          label_idx: 3 # 1-based
          double: 'No'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/E129.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/E129.gc.feather'
      Noonan:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/Noonan.txt_out/label.hdf5'
          name: 'data/Noonan_union.bed.sorted.intersect'
          label_idx: 4 # 1-based
          double: 'No'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/Noonan.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/Noonan.gc.feather'
