reweight: '1'
deepsea-ATACseq.reweight:
  group1:
    info: 'train_deepsea'
    data:
      hNSC-50:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/type1-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-50.gc.feather'
      hNSC-P15-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/type1-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P15-1.gc.feather'
      hNSC-P5-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/type1-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-1.gc.feather'
      hNSC-P5-2:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/type1-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-2.gc.feather'
  group2:
    info: 'JASPAR-logistic'
    data:
      hNSC-50:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-logistic-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-50.gc.feather'
      hNSC-P15-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-logistic-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P15-1.gc.feather'
      hNSC-P5-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-logistic-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-1.gc.feather'
      hNSC-P5-2:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-logistic-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-2.gc.feather'
  group3:
    info: 'JASPAR-svm'
    data:
      hNSC-50:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-svm-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-50.gc.feather'
      hNSC-P15-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-svm-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P15-1.gc.feather'
      hNSC-P5-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-svm-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-1.gc.feather'
      hNSC-P5-2:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/JASPAR-svm-ATACseq_deepsea.ypred.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-2.gc.feather'
  group4:
    info: 'gkmsvm'
    data:
      hNSC-50:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train-ATACseq_hNSC-50.3.deepsea_test-ATACseq.hdf5'
          name: 'y_pred'
          label_idx: 1 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-50.gc.feather'
      hNSC-P15-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train-ATACseq_hNSC-P15-1.1.deepsea_test-ATACseq.hdf5'
          name: 'y_pred'
          label_idx: 2 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P15-1.gc.feather'
      hNSC-P5-1:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train-ATACseq_hNSC-P5-1.1.deepsea_test-ATACseq.hdf5'
          name: 'y_pred'
          label_idx: 3 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-1.gc.feather'
      hNSC-P5-2:
        y:
          path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0629_ATACseq_merged/DeepSEA_test_12__with_label_with_label.hdf5'
          name: 'traindata'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        ypred:
          path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train-ATACseq_hNSC-P5-2.1.deepsea_test-ATACseq.hdf5'
          name: 'y_pred'
          label_idx: 4 # 1-based
          double: 'Yes'
          remove: 'None'
        gc: '../gc_content/results/deepsea_hNSC-P5-2.gc.feather'
