motifs: 'motifs/pfm_vertebrates.txt'
niter: 50
thresold: 2 # LLR (base = 2) threshold to tell whether the sequence contains the motif
data:
  train:
    x:
    y: # in standard format
  valid:
    x:
    y: # in standard format
