task_name: 'JASPAR-ATAC053018'
JASPAR-ATAC053018:
  motifs: 'motifs/pfm_vertebrates.txt'
  background: '0.27665749,0.22330697,0.22330697,0.27665749'
  niter: 80
  threshold: 2 # LLR (base = 2) threshold to tell whether the sequence contains the motif
  data:
    train:
      x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/train_all.h5'
      y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_train_12__with_label_with_label.hdf5' # in standard format
    valid:
      x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/valid_all.h5'
      y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_valid_12__with_label_with_label.hdf5' # in standard format
Training:
  1e-8:
    l1: 0
    l2: 1e-8
  1e-7:
    l1: 0
    l2: 1e-7
  1e-6:
    l1: 0
    l2: 1e-6
  1e-5:
    l1: 0
    l2: 1e-5
  1e-4:
    l1: 0
    l2: 1e-4
  1e-3:
    l1: 0
    l2: 1e-3
  1e-2:
    l1: 0
    l2: 1e-2
  1e-1:
    l1: 0
    l2: 1e-1
  1e0:
    l1: 0
    l2: 1
  1e1:
    l1: 0
    l2: 10
  1e2:
    l1: 0
    l2: 100
partition: 'gpu2'
type_of_head: 'svm'
selected_head:
  best: ''
path: '/scratch/midway2/xinhe/repo/deep_variant/'
