label:
  CN: 1
  DN: 2
  GA: 3
  ips: 4
  NSC: 5
training_data:
  deepsea_train-ATAC053018:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/train_all.h5'
    y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_train_12__with_label.hdf5'
validation_data:
  deepsea_test-ATAC053018:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    y: 'None' # It is not needed
size: 5000 # Per label, not used in testing phase
repeat: 3
seed: 2017
window_size: 300
thread: 4
cache: 6000
