label:
  hNSC-50: 1
  hNSC-P15-1: 2
  hNSC-P5-1: 3
  hNSC-P5-2: 4
training_data:
  deepsea_train-ATACseq:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/train_all.h5'
    y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_train_12__with_label.hdf5'
validation_data:
  deepsea_test-ATACseq:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    y: 'None' # It is not needed
size: 5000 # Per label, not used in testing phase
repeat: 3
seed: 2017
window_size: 300
thread: 4
cache: 6000
