label:
  CN: 1
  DN: 2
  GA: 3
  ips: 4
  NSC: 5
training_data:
  deepsea_train-ATAC053018:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/train_all.h5'
    y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_train_12__with_label_with_label.hdf5'
validation_data:
  deepsea_valid-ATAC053018:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/valid_all.h5'
    y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/atac-seq_053018_merged/DeepSEA_valid_12__with_label_with_label.hdf5'
size: 5000 # per label
repeat: 3
seed: 2017
window_size: 300
thread: 4
cache: 6000
working_dir: '/scratch/midway2/xinhe/repo/deep_variant/gkm_svm'
