label:
  E081: 1
  E082: 2
  E129: 3
  Noonan: 4
training_data:
  deepsea_train:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/train_all.h5'
    y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_train_12__with_label.hdf5'
validation_data:
  deepsea_valid:
    x: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/valid_all.h5'
    y: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/my_train/DeepSEA_valid_12__with_label.hdf5'
size: 50000 # per label
repeat: 3
seed: 2017
window_size: 300
thread: 4
cache: 30000
