model_name: 'gkm_svm'
label:
  E081: 1
  E082: 2
  E129: 3
  Noonan: 4
training_data:
  deepsea_train: 'path_to_training_set_in_hdf5'
validation_data:
  deepsea_valid: 'path_to_validation_set_in_hdf5'
size: 50000 # per label
repeat: 3
seed: 2017
