method:
  mutagensis:
    snakemake: '_mutagensis.snakemake'
  sliding_window:
    snakemake: '_sliding_window.snakemake'
    # mask_size: 22
    # window_size: 50
    quantile: 0.001
    merge: '0'
  motif_gradient:
    snakemake: '_motif_gradient.snakemake'
  motif_activation:
    snakemake: '_motif_activation.snakemake'
reweight: '1'
model:
  name: 'Type1'
  path: '../train_deepsea/model/DeepSEA-ATACseq_logistic.best.hdf5'
  first_layer_idx: 1 # 0-based
  motif_layer_idx: 0 # 0-based
  nmotifs: 320
  lmotif: 8 # length of the motif
  test_data: # only for PWM visualization
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/valid_all.h5'
    name: 'trainxdata'
  motif_of_interest:
    newseq.matchgc.hNSC-50: ''
newseq.matchgc:
  hNSC-50:
    data_name: 'hNSC-50'
    extract_num: 1000
    label_num: 1 # label index in model
    y:
      path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0628_binize_ATACseq/hNSC_50.txt_out/label.hdf5'
      name: 'data/Noonan_hNSC_50_peaks.bed.sorted.intersect'
      label_idx: 1 # 1-based
      double: 'No'
      remove: 'None'
    ypred:
      path: '/project2/xinhe/yanyul/repo/deep_variant/prediction/result/type1-ATACseq_hNSC-50.ypred.hdf5'
      name: 'y_pred'
      label_idx: 1 # 1-based
      double: 'Yes'
      remove: 'None'
    x:
      path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/0628_binize_ATACseq/hNSC_50.txt_out/Noonan_hNSC_50_peaks.bed.sorted_bin200.bed.sorted.merged.final.expended.hdf5'
      name: 'trainxdata'
    gc: '../gc_content/results/hNSC-50.gc.feather'
