http: 'https://github.com/liangyy/deep_variant/blob/code/motif_analysis/'
method:
  mutagensis:
    snakemake: '_mutagensis.snakemake'
  sliding_window:
    snakemake: '_sliding_window.snakemake'
    mask_size: 8
  motif_gradient:
    snakemake: '_motif_gradient.snakemake'
  motif_activation:
    snakemake: '_motif_activation.snakemake'
model:
  name: 'Type1'
  path: '../../../deep_variant/yanyu/deep_brain/my_train/keras_deepsea_with_040417_2_42_head.hdf5'
  first_layer_idx: 1 # 0-based
  motif_layer_idx: 0 # 0-based
  nmotifs: 320
  lmotif: 8 # length of the motif
  test_data: # only for PWM visualization
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/valid_all.h5'
    name: 'trainxdata'
  motif_of_interest:
    combined: '302,24,69,119,246,9,37,245,150,96,55,300,78,118,214,22,222,0'
    activation: '185,106,29,4,275,78,291,278,125,100'
data:
  E081:
    data_name: 'E081'
    label_num: 1 # 1-based
    extract_num: 1000
    # seed: 2017
    data_ypred:
      path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
      name: 'y_pred'
    data_y:
      path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
      name: 'traindata'
    data_x:
      path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
      name: 'trainxdata'
  E082:
    data_name: 'E082'
    label_num: 2 # 1-based
    extract_num: 1000
    # seed: 2017
    data_ypred:
      path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
      name: 'y_pred'
    data_y:
      path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
      name: 'traindata'
    data_x:
      path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
      name: 'trainxdata'
  Noonan:
    data_name: 'Noonan'
    label_num: 4 # 1-based
    extract_num: 1000
    # seed: 2017
    data_ypred:
      path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
      name: 'y_pred'
    data_y:
      path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
      name: 'traindata'
    data_x:
      path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
      name: 'trainxdata'
