channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - graphviz=2.38.0
  - python=3.5.1
  - snakemake=3.11.0
  - pyyaml=3.11
  - bedtools=2.25.0
  - pip
  - feather-format
  - pip:
    - ipython
    - h5py
    - keras==2.0.0
    - theano
    - pandas
