summary:
  extracted: 'E081,E082,Noonan,E129'
  deepsea: 'deepsea_E081,deepsea_E082,deepsea_Noonan,deepsea_E129'
  test: 'E081,E082'
E081:
  data_ypred:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E081.txt_out/E081-DNase.macs2.narrowPeak_bin200.bed.sorted.merged.final.expended_keras_deepsea_12_42-0.1703-0.1520_pred.hdf5'
    name: 'y_pred'
    double: 'No'
    remove: 'None'
    label_num: 1
  data_y:
    label_num: -1 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E081.txt_out/label.hdf5'
    name: 'data/E081-DNase.macs2.narrowPeak.sorted.intersect'
    double: 'No'
    remove: '1073109-1073114'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E081.txt_out/E081-DNase.macs2.narrowPeak_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
E082:
  data_ypred:
    label_num: 2
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E082.txt_out/E082-DNase.macs2.narrowPeak_bin200.bed.sorted.merged.final.expended_keras_deepsea_12_42-0.1703-0.1520_pred.hdf5'
    name: 'y_pred'
    double: 'No'
    remove: 'None'
  data_y:
    label_num: -1
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E082.txt_out/label.hdf5'
    name: 'data/E082-DNase.macs2.narrowPeak.sorted.intersect'
    double: 'No'
    remove: '1238543-1238548'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E082.txt_out/E082-DNase.macs2.narrowPeak_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
Noonan:
  data_ypred:
    label_num: 4
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/Noonan.txt_out/Noonan_union.bed_bin200.bed.sorted.merged.final.expended_keras_deepsea_12_42-0.1703-0.1520_pred.hdf5'
    name: 'y_pred'
    double: 'No'
    remove: 'None'
  data_y:
    label_num: -1
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/Noonan.txt_out/label.hdf5'
    name: 'data/Noonan_union.bed.sorted.intersect'
    double: 'No'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/Noonan.txt_out/Noonan_union.bed_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
E129:
  data_ypred:
    label_num: 3
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E129.txt_out/E129-H3K9me3.narrowPeak_bin200.bed.sorted.merged.final.expended_keras_deepsea_12_42-0.1703-0.1520_pred.hdf5'
    name: 'y_pred'
    double: 'No'
    remove: 'None'
  data_y:
    label_num: -1
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E129.txt_out/label.hdf5'
    name: 'data/E129-H3K9me3.narrowPeak.sorted.intersect'
    double: 'No'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/040917_binize_datasets/E129.txt_out/E129-H3K9me3.narrowPeak_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_E081:
  data_ypred:
    label_num: 1
    path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 1
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_E082:
  data_ypred:
    label_num: 2
    path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 2
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_Noonan:
  data_ypred:
    label_num: 4
    path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 4
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_E129:
  data_ypred:
    label_num: 3
    path: '../../../deep_variant/yanyu/deep_brain/my_train/040417_overnight/2/42-0.1703-0.1520_DeepSEA_test_12__with_label.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 3
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
