summary:
  extracted-paperNSC: 'd27,d41-1,d41-2'
  deepsea-paperNSC: 'deepsea_d27,deepsea_d41-1,deepsea_d41-2'
d27:
  data_ypred:
    path: '/scratch/midway2/xinhe/deep_variant/prediction/result/type1-paperNSC_d27.ypred.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
    label_num: 1
  data_y:
    label_num: -1 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_binize/d27.txt_out/label.hdf5'
    name: 'data/GSM1820082_d27_fdr0.05.hot.bed.sorted.intersect'
    double: 'No'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_binize/d27.txt_out/GSM1820082_d27_fdr0.05.hot.bed.sorted_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
d41-1:
  data_ypred:
    path: '/scratch/midway2/xinhe/deep_variant/prediction/result/type1-paperNSC_d41-1.ypred.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
    label_num: 2
  data_y:
    label_num: -1 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_binize/d41_1.txt_out/label.hdf5'
    name: 'data/GSM1820085_d411_fdr0.05.hot.bed.sorted.intersect'
    double: 'No'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_binize/d41_1.txt_out/GSM1820085_d411_fdr0.05.hot.bed.sorted_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
d41-2:
  data_ypred:
    path: '/scratch/midway2/xinhe/deep_variant/prediction/result/type1-paperNSC_d41-2.ypred.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
    label_num: 3
  data_y:
    label_num: -1 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_binize/d41_2.txt_out/label.hdf5'
    name: 'data/GSM1820087_d412_fdr0.05.hot.bed.sorted.intersect'
    double: 'No'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_binize/d41_2.txt_out/GSM1820087_d412_fdr0.05.hot.bed.sorted_bin200.bed.sorted.merged.final.expended.hdf5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_d27:
  data_ypred:
    path: '/scratch/midway2/xinhe/deep_variant/prediction/result/type1-paperNSC_deepsea.ypred.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
    label_num: 1
  data_y:
    label_num: 1 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_merged/DeepSEA_test_12__with_label_with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_d41-1:
  data_ypred:
    path: '/scratch/midway2/xinhe/deep_variant/prediction/result/type1-paperNSC_deepsea.ypred.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
    label_num: 2
  data_y:
    label_num: 2 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_merged/DeepSEA_test_12__with_label_with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_d41-2:
  data_ypred:
    path: '/scratch/midway2/xinhe/deep_variant/prediction/result/type1-paperNSC_deepsea.ypred.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
    label_num: 3
  data_y:
    label_num: 3 # 1-based
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/test/1012_gse70823_merged/DeepSEA_test_12__with_label_with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '/project2/xinhe/yanyul/deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
