summary:
  deepsea_gkm: 'deepsea_E081_gkm,deepsea_E082_gkm,deepsea_Noonan_gkm,deepsea_E129_gkm'
deepsea_E081_gkm:
  data_ypred:
    label_num: 1
    path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_E081.3.deepsea_test.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 1
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_E082_gkm:
  data_ypred:
    label_num: 2
    path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_E082.1.deepsea_test.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 2
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_Noonan_gkm:
  data_ypred:
    label_num: 4
    path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_Noonan.2.deepsea_test.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 4
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
deepsea_E129_gkm:
  data_ypred:
    label_num: 3
    path: '/project2/xinhe/yanyul/repo/deep_variant/gkm_svm/result/deepsea_train_E129.3.deepsea_test.hdf5'
    name: 'y_pred'
    double: 'Yes'
    remove: 'None'
  data_y:
    label_num: 3
    path: '../../../deep_variant/yanyu/deep_brain/my_train/DeepSEA_test_12__with_label.hdf5'
    name: 'traindata'
    double: 'Yes'
    remove: 'None'
  data_x:
    path: '../../../deep_variant/yanyu/DanQ/my_train/data/test_all.h5'
    name: 'trainxdata'
    double: 'Yes'
