stage1stage2:
  1.E081: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E081-DNase.macs2.narrowPeak.sorted'
  2.E082: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E082-DNase.macs2.narrowPeak.sorted'
  3.Noonan: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_union.bed.sorted'
  4.E129: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E129-H3K9me3.narrowPeak.sorted'
  5.hNSC-50: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_50_peaks.bed.sorted'
  6.hNSC-P5-1: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_P5-1_peaks.bed.sorted'
  7.hNSC-P5-2: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_P5-2_peaks.bed.sorted'
  8.hNSC-P15-1: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_P15-1_peaks.bed.sorted'
  9.Chorion-DNase: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/Chorion-DNase.sorted'
  10.NH-A-CTCF: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-CTCF.sorted'
  11.NH-A-DNase: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-DNase.sorted'
  12.NH-A-EZH2: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-EZH2.sorted'
  13.NH-A-H2AZ: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H2AZ.sorted'
  14.NH-A-H3K27ac: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K27ac.sorted'
  15.NH-A-H3K27me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K27me3.sorted'
  16.NH-A-H3K27ac: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K27ac.sorted'
  17.NH-A-H3K36me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K36me3.sorted'
  18.NH-A-H3K4me1: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K4me1.sorted'
  19.NH-A-H3K4me2: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K4me2.sorted'
  20.NH-A-H3K4me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K4me3.sorted'
  21.NH-A-H3K79me2: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K79me2.sorted'
  22.NH-A-H3K9ac: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K9ac.sorted'
  23.NH-A-H3K9me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K9me3.sorted'
  24.NH-A-H4K20me1: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H4K20me1.sorted'


  
  











