stage1stage2:
  a1.E081: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E081-DNase.macs2.narrowPeak.sorted'
  a2.E082: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E082-DNase.macs2.narrowPeak.sorted'
  a3.Noonan: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_union.bed.sorted'
  a4.E129: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/E129-H3K9me3.narrowPeak.sorted'
  a5.hNSC-50: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_50_peaks.bed.sorted'
  a6.hNSC-P5-1: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_P5-1_peaks.bed.sorted'
  a7.hNSC-P5-2: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_P5-2_peaks.bed.sorted'
  a8.hNSC-P15-1: '/project2/xinhe/yanyul/deep_variant/yanyu/deep_brain/data/Noonan_hNSC_P15-1_peaks.bed.sorted'
  b1.Chorion-DNase: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/Chorion-DNase.sorted'
  b2.NH-A-CTCF: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-CTCF.sorted'
  b3.NH-A-DNase: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-DNase.sorted'
  b4.NH-A-EZH2: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-EZH2.sorted'
  b5.NH-A-H2AZ: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H2AZ.sorted'
  b6.NH-A-H3K27ac: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K27ac.sorted'
  b7.NH-A-H3K27me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K27me3.sorted'
  b8.NH-A-H3K27ac: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K27ac.sorted'
  b9.NH-A-H3K36me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K36me3.sorted'
  c1.NH-A-H3K4me1: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K4me1.sorted'
  c2.NH-A-H3K4me2: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K4me2.sorted'
  c3.NH-A-H3K4me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K4me3.sorted'
  c4.NH-A-H3K79me2: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K79me2.sorted'
  c5.NH-A-H3K9ac: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K9ac.sorted'
  c6.NH-A-H3K9me3: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H3K9me3.sorted'
  c7.NH-A-H4K20me1: '/project2/xinhe/yanyul/repo/deep_variant/download_annotation/data/NH-A-H4K20me1.sorted'


  
  











