---
title: "Motif Analysis - motif activation"
output:
    html_document:
        number_sections: true
        toc: true
        toc_depth: 3
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup}
knitr::opts_knit$set(root.dir = '../../')
```

# Overall Activation

```{r}
source('scripts/my_r.R')
library(feather)
library(ggplot2)
library(reshape2)
library(bsselectR)
info <- c('Type1', 'E082', 'motif_activation')
pos <- load_and_melt('pattern/Type1/E082/motif_activation/pattern_positive.feather')
neg <- load_and_melt('pattern/Type1/E082/motif_activation/pattern_negative.feather')
ggplot(pos$table.melted) + geom_raster(aes(x = variable, y = id, fill = value)) + scale_fill_gradient2() + ggtitle('Activation per sequence (Positive)') + labs(x = 'motif', y = 'sequence')
ggplot(neg$table.melted) + geom_raster(aes(x = variable, y = id, fill = value)) + scale_fill_gradient2() + ggtitle('Activation per sequence (Negative)') + labs(x = 'motif', y = 'sequence')
```

# Per Motif Activation

```{r}
pvalues <- c()
motifs <- c()
for(i in colnames(pos$table)){
    if(i != 'id'){
        poss <- pos$table[[i]]
        negs <- neg$table[[i]]
        pvalues <- c(pvalues, wilcox.test(poss, negs)$p.value)
        motifs <- c(motifs, i)
    }
}
df <- data.frame(motif=motifs, p.value=pvalues)
```

## Motif activation comparison (positive vs negative)

```{r, echo=FALSE, warning=FALSE}
motif.ordered <- order(df$p.value)
motifs <- unique(pos$table.melted$variable)
motif.all <- motifs[motif.ordered]
pvalue.all <- df$p.value[motif.ordered]
plots <- list()
for(i in 1 : length(motif.all)){
    p <- plot_motif(pos$table.melted, neg$table.melted, motif.all[i], pvalue.all[i])
    plots <- save_plot(info, p, motif.all[i], 'plots', plots)
}
bsselect(plots, type = "img", selected = motif.all[1],
         live_search = TRUE, show_tick = TRUE, height = 5)
```
```{r, echo=FALSE, warning=FALSE}
bsselect(plots, type = "img", selected = motif.all[2],
         live_search = TRUE, show_tick = TRUE, height = 5)
```

