# this module takes an HDF5 training data and split it into training and validation sets

rule all:
    input:
        'output/{name}.train.hdf5'.format(name = list(config.keys())[0]),
        'output/{name}.valid.hdf5'.format(name = list(config.keys())[0])

rule split:
    input:
        x = lambda wildcards: config[wildcards.name]['x'],
        y = lambda wildcards: config[wildcards.name]['y']
    params:
        lambda wildcards: config[wildcards.name]['fold']
    output:
        'output/{name}.train.hdf5',
        'output/{name}.valid.hdf5'
    shell:
        'python scripts/split.py --x {input.x} --y {input.y} --fold {params[0]} --prefix output/{wildcards.name}'
