---
title: "Motif Analysis - GC content of selected sequences"
output:
    html_document:
        number_sections: true
        toc: true
        toc_depth: 3
        toc_float: true
date: "`r format(Sys.time(), '%B %d, %Y')`"
---

```{r setup}
knitr::opts_knit$set(root.dir = '../../')
```

# Distribution of GC content

```{r, echo=TRUE, warning=FALSE}
library(feather)
library(ggplot2)
library(bsselectR)
envir <- '../../'
prefix <- 'newseq.matchgc'
filelist <- 'E081,E082,Noonan'
file_prefixs <- strsplit(filelist, ',')[[1]]
for(i in file_prefixs){
    e <- read_feather(paste0('./data/', prefix, '.', i, '/gc.feather'))
    p <- ggplot() + geom_density(data = e[e$y == 0, ], aes(x = GC.Content, fill = 'negative'), alpha = .5) + geom_density(data = e[e$y == 1, ], aes(x = GC.Content,  fill = 'positive'), alpha = .5) + ggtitle(paste0('GC content of data in ', i)) + theme(legend.position="bottom") + theme(title = element_text(size=5), text = element_text(size=5))
    ggsave(filename = paste0(prefix, '_', i, '_hist.png'), path = 'plots/', width = 3, height = 3, plot = p)
}
plots <- list()
for(i in file_prefixs){
    plots[[i]] <- paste0(envir, '/plots/', paste0(prefix, '_', i, '_hist.png'))
}
bsselect(plots, type = "img", selected = names(plots)[2],
         live_search = TRUE, show_tick = TRUE, height = 5, width = 5, frame_height = 500, frame_width = 500)
```
